version: '3.8'

services:
  youtube-generator:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: youtube-generator-prod
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/app
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3 